# SonarCloud — completar los TODO antes de usar.
# El SONAR_TOKEN va como GitHub Secret (no aquí).
sonar.projectKey=frontend-cursos
sonar.organization=jdelcastillos-pucp

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
sonar.exclusions=src/courses.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
